---
- name: Install, start and enabled Apache, Upload webpage to server
  hosts: ubuntu
  become: yes

  vars:
    source_dir: ./webpage/
    destin_dir: /var/www/html/

  tasks:
  - name: Update packages 
    apt:
      update_cache: True
      upgrade: True
  
  - name: Install Apache WebServer
    apt: name=apache2 state=latest

  - name: Copy Web Page to destination directory
    copy: src={{ source_dir }} dest={{ destin_dir }} mode=0555

  - name: Started and enabled Apache
    service: name=apache2 state=started enabled=yes
...
